### ISSUE TITLE
The Recent Commit FD70c8D Breaks Non-Default Initial Conditions

### ISSUE THREAD

**Issue by ryanpeach** [HermannBjorgvin/Gravity-Experiments#10]
If you press "clear system" and then right click (or even if you right click and then click "clear system") you will no longer be able to create objects.

**Comment by HermannBjorgvin** [comment]
See it now. Interesting bug. Don't have much time to work on this right now but I'll put it on the back burner. You can also have a create a PR yourself if you're brave enough to traverse my code.

Cheers
