### ISSUE TITLE
Gravity Attracts During Reverse Time Acceleration

### ISSUE THREAD

**Issue by ryanpeach** [HermannBjorgvin/Gravity-Experiments#12]
Reversing time ought to make gravity repulsive.

**Comment by ryanpeach** [comment]
Wait, unsure... Would it?

**Comment by ryanpeach** [comment]
I found the issue, it was just a misunderstanding with creating objects in reverse-time mode.

**Comment by HermannBjorgvin** [comment]
Not really, it just does the calculation backwards, it's actually more of a bug than a feature really, didn't mean for people to be able to reverse the calculation.

**Comment by ryanpeach** [comment]
It's cool that you can teach people that time is really just a variable in these things.
