### ISSUE TITLE
Some improvements sugestion

### ISSUE THREAD

**Issue by ricardofiorani** [HermannBjorgvin/Gravity-Experiments#6]
Hi @HermannBjorgvin ,

I believe this project has potential to be used in schools to teach the basic concepts of gravity.
It would be a very nice tool to be used by teachers around the world.

For this, it need some improvements:
- Translation to more languages
- We could use texture on the objects to look more like astronomical objects. The purpose of this is to make the UI to look more like a "game" to get interest of kids. These textures can be provided by some  free to use video game assets website.
- Make it usable in mobile/tablets. For this we could:
  - Make the menu visibility togglable by some button (to get more space)
  - Detect both events from mouse and from touch
- Make it able to save and load (from cookies maybe ?) the created systems.
- Would be nice if right clicking an object and it shows some info like it's mass and speed.
- A Pause button (it just sets the calculation speed to 0)
- The calculation speed should never be negative, since the we can not guarantee that the objects states will be the same.
- When creating a new object, we could show a line to preview the direction that the object would take. It would help a lot to create systems.

All of these are just my opinion of improvements that would be nice, but it might take the project to a whole new direction that you may not like or don't want for it.
I'm likely to do most of these improvements in my free times, but I would like to know about what you think about this.

**Comment by HermannBjorgvin** [comment]
Yeah @ricardofiorani , all sounds like good changes. The realistic looking texture you did were awesome.

I suggest we start again with a cleaner API and a better plan for the UI, set up JSON translation files so people can translate it to any language. I've also always wanted to add a touch component to this, and add a simpler massbuilder for creating objects, that would make things easier and more fun for creating orbiting bodies (touch is also ridiculously kid friendly as you mentioned).

When creating a new object thought it's hard to preview the path it will take without actually calculating it. We could simplify the GUI though and just have an option to create a body that orbits the focused object when you click (easy formula available).

I'm also working on a barnes-hut algorithm right now that would be much much faster than the current one, it's going to have the same spacetime API so it's a drop-in replacement.

Anyway, all for the kid friendlier UI, should be a really cool addition
